-- begin ENTITYPIN_ORDER
alter table ENTITYPIN_ORDER add constraint FK_ENTITYPIN_ORDER_CUSTOMER foreign key (CUSTOMER_ID) references ENTITYPIN_CUSTOMER(ID)^
create index IDX_ENTITYPIN_ORDER_CUSTOMER on ENTITYPIN_ORDER (CUSTOMER_ID)^
-- end ENTITYPIN_ORDER
